# Generated by Django 3.1.1 on 2020-12-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eddr',
            new_name='eaddr',
        ),
    ]
