# Generated by Django 3.1.1 on 2020-12-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Country', 'Country'), ('Jazz', 'Jazz'), ('Blues', 'Blues')], max_length=30),
        ),
    ]
